Login connection with api Co-authored-by: Jazmin chavez <gracielajazm…
BC-NOV-20-Proyectos/alerta-covid-mobile-team-01 pull request #12
Opened 2021-04-09 22:10 UTC by Joaquin-Niembro

…in_chavez@ucol.mx> Co-authored-by: Genesis Zarate <genesis.zarate94@gmail.com>

# Description
- We implemented the http request to the Api using Redux and Axios.
- Users are now able to log in with their accounts.
- User´s sessions are persited with redux persist.
 
 # Testing
-git clone repository
-git switch feature#11/LoginApi
-npm install
-npm run start
-npm run android/ios

2021-04-09 22:12 UTC, fernandoamz requested changes

2021-04-09 22:12 UTC, fernandoamz commented on AlertaCovid/src/redux/actions/AuthActions.js
> +        `https://hidden-cliffs-21927.herokuapp.com/api/user/sign_in?api_user[email]=${email}&api_user[password]=${password}`,
Refactor this, adding the api url on constants file and concat de vars

2021-04-12 15:27 UTC, fernandoamz approved these changes

2021-04-12 15:45 UTC, fernandoamz approved these changes

2021-04-12 16:04 UTC, jjcr11 approved these changes

2021-04-12 16:05 UTC, mariam-rivera approved these changes

2021-04-12 16:05 UTC, merged