Feature#1/ui login
BC-NOV-20-Proyectos/alerta-covid-mobile-team-01 pull request #2
Opened 2021-03-12 21:22 UTC by Joaquin-Niembro

# Description
What did you implemented/Why did you implemented this:
-Implemeneted the UI design and coded it.
-Form validation using Formik.
 
 # Testing
-Git clone repo
-git branch Feature#1uilogin
-npm install
-npm run start
-npm run android
 
  ## Screenshots 
![Frame 1](https://user-images.githubusercontent.com/67522982/110999886-b1457280-8346-11eb-8845-0cd298e31f88.png)

2021-03-12 21:32 UTC, LeyaimMagma requested changes

2021-03-12 21:32 UTC, LeyaimMagma commented on AlertaCovid/src/styles/WelcomeStyles/index.js
> +})
Always a blank space at the end

2021-03-12 21:32 UTC, LeyaimMagma commented on AlertaCovid/src/styles/index.js
> +export * from './SignIn'
Always a blank space at the end

2021-03-12 21:32 UTC, LeyaimMagma commented on AlertaCovid/src/utils/constants/index.js
> +}
Always a blank space at the end

2021-03-12 21:32 UTC, LeyaimMagma commented on AlertaCovid/src/utils/index.js
> +export * from './constants'
Always a blank space at the end

2021-03-12 21:42 UTC, fernandoamz requested changes
some files have the indentation with 4 spaces and should be 2

2021-03-13 01:51 UTC, ChantalRamirez approved these changes, later dismissed
Excelent design

2021-03-16 22:08 UTC, LeyaimMagma approved these changes

2021-03-17 16:32 UTC, fernandoamz approved these changes

2021-03-17 16:40 UTC, ChantalRamirez approved these changes

2021-03-17 16:42 UTC, merged